name: Check SWC Update

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * *'

jobs:
  check-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: latest
          run_install: true
      - name: Run checker script
        run: pnpm tsx scripts/check-swc-update.mts
      - name: Commit update
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: upgrade SWC
          file_pattern: .env
